global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'broker'
    file_sd_configs:
    - files:
      - 'targets.json'
      
  - job_name: 'fluentd'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '10.0.3.248:9000'
        - '10.0.1.51:9000'
        - '10.0.3.253:9000'
        - '10.0.1.70:9000'
        - '10.0.2.21:9000'
        - '10.0.3.159:9000'
        - '10.0.2.162:9000'
        - '10.0.1.77:9000'
        - '10.0.2.107:9000'
        - '10.0.1.35:9000'
        - '10.0.2.242:9000'
        - '10.0.3.44:9000'
        - '10.0.1.93:9000'
        - '10.0.3.244:9000'
        - '10.0.2.241:9000'
        - '10.0.3.48:9000'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
