global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'broker'
    file_sd_configs:
    - files:
      - 'targets.json'
      
  - job_name: 'fluentd'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '10.0.3.249:9000'
        - '10.0.3.122:9000'
        - '10.0.2.83:9000'
        - '10.0.2.37:9000'
        - '10.0.1.85:9000'
        - '10.0.1.202:9000'
        - '10.0.3.166:9000'
        - '10.0.2.135:9000'
        - '10.0.1.210:9000'
        - '10.0.3.100:9000'
        - '10.0.1.93:9000'
        - '10.0.2.163:9000'
        - '10.0.2.88:9000'
        - '10.0.2.5:9000'
        - '10.0.3.67:9000'
        - '10.0.1.213:9000'
        - '10.0.1.16:9000'
        - '10.0.2.99:9000'
        - '10.0.3.116:9000'
        - '10.0.3.38:9000'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
