global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'broker'
    file_sd_configs:
    - files:
      - 'targets.json'
      
  - job_name: 'fluentd'
    scrape_interval: 10s
    static_configs:
      - targets:
        - '10.0.1.190:9000'
        - '10.0.1.188:9000'
        - '10.0.3.219:9000'
        - '10.0.3.64:9000'
        - '10.0.2.128:9000'
        - '10.0.3.157:9000'
        - '10.0.1.182:9000'
        - '10.0.2.132:9000'
        - '10.0.2.36:9000'
        - '10.0.2.91:9000'
        - '10.0.3.192:9000'
        - '10.0.1.107:9000'
        - '10.0.3.145:9000'
        - '10.0.1.196:9000'
        - '10.0.1.118:9000'
        - '10.0.2.63:9000'
        - '10.0.3.211:9000'
        - '10.0.1.14:9000'
        - '10.0.2.109:9000'
        - '10.0.2.198:9000'
        
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'

#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
