{
 "title": "Kafka Consumer",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P99 E2E latency (Approximation)",
   "type": "timeseries",
   "description": "P99 difference between producer and consumer timestamp (Aggregated across 1 minute)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(e2e_latency_seconds_bucket[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Avg E2E latency (Approximation)",
   "type": "timeseries",
   "description": "Average difference between producer and consumer timestamp (Aggregated across 1 minute)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(e2e_latency_seconds_sum[1m])\n/\nrate(e2e_latency_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "E2E Latency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(e2e_latency_seconds_bucket[$__rate_interval])) by (le)"
    }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 } }
 ]
}